import type {
  Contact,
  LiveUtterance,
  Session,
  UnknownQueueItem,
  Utterance,
} from '../types/domain'

export const contacts: Contact[] = [
  {
    id: 'c1',
    name: 'Олена Ковальчук',
    initials: 'ОК',
    color: '#7C6FFF',
    sessions: 12,
    totalTime: 3840,
    firstMet: '3 листопада 2024',
    languages: ['UK'],
    profileCount: 18,
    confidence: 0.91,
    pitch: 'середній',
    tempo: 'середній',
    energy: 67,
    pitchHz: 164,
  },
  {
    id: 'c2',
    name: 'Микола Бойко',
    initials: 'МБ',
    color: '#3DD68C',
    sessions: 8,
    totalTime: 1620,
    firstMet: '15 січня 2025',
    languages: ['UK', 'EN'],
    profileCount: 11,
    confidence: 0.84,
    pitch: 'низький',
    tempo: 'повільний',
    energy: 45,
    pitchHz: 118,
  },
  {
    id: 'c3',
    name: 'Тарас Щербань',
    initials: 'ТЩ',
    color: '#F59E0B',
    sessions: 5,
    totalTime: 940,
    firstMet: '20 лютого 2025',
    languages: ['UK'],
    profileCount: 6,
    confidence: 0.76,
    pitch: 'середній',
    tempo: 'швидкий',
    energy: 74,
    pitchHz: 155,
  },
  {
    id: 'c4',
    name: 'Іванна Петренко',
    initials: 'ІП',
    color: '#EC4899',
    sessions: 3,
    totalTime: 480,
    firstMet: '10 березня 2025',
    languages: ['EN'],
    profileCount: 4,
    confidence: 0.68,
    pitch: 'високий',
    tempo: 'середній',
    energy: 58,
    pitchHz: 218,
  },
  {
    id: 'c5',
    name: 'Андрій Лисенко',
    initials: 'АЛ',
    color: '#06B6D4',
    sessions: 7,
    totalTime: 2100,
    firstMet: '5 грудня 2024',
    languages: ['UK', 'EN'],
    profileCount: 9,
    confidence: 0.87,
    pitch: 'низький',
    tempo: 'середній',
    energy: 52,
    pitchHz: 109,
  },
]

export const sessions: Session[] = [
  {
    id: 's1',
    title: 'Стендап команди продукту',
    date: '22 квіт 2026',
    time: '10:15',
    duration: '18:34',
    utteranceCount: 47,
    languages: ['UK'],
    speakers: ['c1', 'c2', 'c3'],
    preview: 'Добре, давайте починати. Олена, що у тебе по бекенду?',
  },
  {
    id: 's2',
    title: "Інтерв'ю з Іванною — UX дослідження",
    date: '21 квіт 2026',
    time: '14:30',
    duration: '43:11',
    utteranceCount: 112,
    languages: ['UK', 'EN'],
    speakers: ['c4', 'c1'],
    preview: 'Розкажіть як ви зазвичай починаєте свій робочий день.',
  },
  {
    id: 's3',
    title: 'Зустріч з Андрієм по архітектурі',
    date: '20 квіт 2026',
    time: '11:00',
    duration: '32:07',
    utteranceCount: 83,
    languages: ['UK'],
    speakers: ['c5', 'c1'],
    preview: 'Я думаю що нам треба переглянути підхід до мікросервісів.',
  },
  {
    id: 's4',
    title: 'Обговорення дизайну нового флоу',
    date: '18 квіт 2026',
    time: '16:45',
    duration: '27:53',
    utteranceCount: 65,
    languages: ['UK'],
    speakers: ['c1', 'c2', 'c3', 'c4'],
    preview: 'Мені подобається загальна концепція, але треба доопрацювати деталі.',
  },
  {
    id: 's5',
    title: 'Q2 roadmap sync',
    date: '17 квіт 2026',
    time: '09:30',
    duration: '12:18',
    utteranceCount: 31,
    languages: ['EN'],
    speakers: ['c2', 'c5'],
    preview: "Let's quickly align on the Q2 roadmap priorities.",
  },
]

export const sessionUtterances: Record<string, Utterance[]> = {
  s1: [
    { id: 'u1', speakerId: 'c2', time: '00:03', text: 'Добре, давайте починати. Олена, що у тебе по бекенду?' },
    { id: 'u2', speakerId: 'c1', time: '00:11', text: 'По бекенду все добре, вчора задеплоїли нову версію API. Є невелика проблема з rate limiting але вже розбираємось.' },
    { id: 'u3', speakerId: 'c2', time: '00:47', text: 'Ясно. Тарасе, як там з фронтом?' },
    { id: 'u4', speakerId: 'c3', time: '00:52', text: 'Закрив три тікети по дашборду. Ще один залишився — там складний edge case.' },
    { id: 'u5', speakerId: 'c1', time: '01:18', text: "Щодо edge case — мені здається це пов'язано зі станом після рефреш. Можемо подивитись разом після стендапу?" },
    { id: 'u6', speakerId: 'c3', time: '01:29', text: 'Так, було б добре.' },
    { id: 'u7', speakerId: null, time: '01:45', text: 'Я хотів би додати — нам треба переглянути документацію до кінця тижня.' },
    { id: 'u8', speakerId: 'c2', time: '02:01', text: 'Погоджуюсь. Хто може взяти це на себе?' },
    { id: 'u9', speakerId: 'c1', time: '02:08', text: 'Я можу зайнятись документацією в четвер. Це займе пів дня максимум.' },
  ],
  s2: [
    { id: 'u1', speakerId: 'c1', time: '00:04', text: 'Розкажіть як ви зазвичай починаєте свій робочий день.' },
    { id: 'u2', speakerId: 'c4', time: '00:12', lang: 'EN', text: 'Usually I start by checking messages and planning tasks for the day.' },
    { id: 'u3', speakerId: 'c1', time: '01:03', text: 'А як ви пріоритизуєте задачі?' },
    { id: 'u4', speakerId: 'c4', time: '01:09', lang: 'EN', text: 'I use a simple system — urgent vs important matrix, mostly.' },
  ],
  s3: [
    { id: 'u1', speakerId: 'c5', time: '00:02', text: 'Я думаю що нам треба переглянути підхід до мікросервісів.' },
    { id: 'u2', speakerId: 'c1', time: '00:18', text: 'Погоджуюсь. Поточна архітектура не масштабується добре при великому навантаженні.' },
    { id: 'u3', speakerId: 'c5', time: '00:41', text: 'Якщо ми перейдемо на event-driven підхід, то latency значно покращиться. Але це потребує рефакторингу трьох сервісів.' },
  ],
}

export const unknownQueue: UnknownQueueItem[] = [
  {
    id: 'q1',
    queueIds: ['q1'],
    segmentIds: ['seg-q1'],
    sessionIds: ['s1'],
    sessionTitles: ['Стендап команди продукту'],
    sessionId: 's1',
    sessionTitle: 'Стендап команди продукту',
    sessionDate: '22 квіт 2026 · 10:15',
    label: 'Q1',
    fragmentCount: 3,
    totalDuration: '1хв 12с',
    quote: 'Я хотів би додати — нам треба переглянути документацію до кінця тижня. Це критично для наступного релізу.',
    candidates: [
      { contactId: 'c5', score: 0.81 },
      { contactId: 'c3', score: 0.71 },
    ],
    status: 'unresolved',
  },
  {
    id: 'q2',
    queueIds: ['q2'],
    segmentIds: ['seg-q2'],
    sessionIds: ['s2'],
    sessionTitles: ["Інтерв'ю з Іванною — UX дослідження"],
    sessionId: 's2',
    sessionTitle: "Інтерв'ю з Іванною — UX дослідження",
    sessionDate: '21 квіт 2026 · 14:30',
    label: 'Q2',
    fragmentCount: 1,
    totalDuration: '23с',
    quote: 'Зазвичай я починаю з перегляду повідомлень і планую задачі на день.',
    candidates: [],
    status: 'unresolved',
  },
  {
    id: 'q3',
    queueIds: ['q3'],
    segmentIds: ['seg-q3'],
    sessionIds: ['s3'],
    sessionTitles: ['Зустріч з Андрієм по архітектурі'],
    sessionId: 's3',
    sessionTitle: 'Зустріч з Андрієм по архітектурі',
    sessionDate: '20 квіт 2026 · 11:00',
    label: 'Q3',
    fragmentCount: 5,
    totalDuration: '3хв 48с',
    quote: 'Якщо ми перейдемо на event-driven підхід, то latency значно покращиться. Але це потребує рефакторингу трьох сервісів.',
    candidates: [{ contactId: 'c2', score: 0.74 }],
    status: 'unresolved',
  },
]

export const liveUtterances: LiveUtterance[] = [
  { speakerId: 'c1', delay: 2800, text: 'Добре, починаємо. Сьогодні обговоримо план на наступний спринт.' },
  { speakerId: 'c2', delay: 4200, text: 'У мене є кілька питань по попередньому спринту — не всі задачі закриті.' },
  { speakerId: 'c1', delay: 3800, text: 'Так, я бачив. Дві задачі перенесли — вони входять в новий спринт автоматично.' },
  { speakerId: null, delay: 5100, text: 'Мені здається нам варто переглянути критерії завершення задач.' },
  { speakerId: 'c3', delay: 3400, text: 'Повністю підтримую. Давайте виділимо 15 хвилин на Definition of Done.' },
  { speakerId: 'c2', delay: 4600, text: "Ок, тоді пропоную в п'ятницю зробити окрему зустріч на цю тему." },
  { speakerId: 'c1', delay: 3200, text: 'Домовились. Я зараз запишу в calendar.' },
  { speakerId: null, delay: 5800, text: 'Ще одне — треба визначитись з пріоритетом технічного боргу в цьому спринті.' },
]

export function contactById(id: string | null | undefined): Contact | null {
  if (!id) return null
  return contacts.find((c) => c.id === id) ?? null
}
